#!/usr/bin/python 

import praw 

reddit = praw.Reddit(user_agent='WeightBot (by /u/phrisky_phrank)',
                     client_id=your personal script id,
                     client_secret=secret ,
                     username = your username, password=your password)


subreddit = reddit.subreddit(any subreddit) #subreddit you want to monitor

bot_phrase = 'Aw shucks, looks like im stayin in >:(' #phrase that the bot replies with

keywords = {'Cold', 'chicago', 'polar', 'vortex'} #add keywords to find in subreddits

for submission in subreddit.hot(limit=15):
    n_title = submission.title.lower()
    for i in keywords:
        if i in n_title:
            print('Bot replying to: ')
            print("Title: ", submission.title)
            print("Text: ", submission.selftext)
            print("Score: ", submission.score)
            print("---------------------------------")
            print('Bot saying: ', bot_phrase)
            print()
            submission.reply(bot_phrase)
